export const HANDLE_CHANGE_LOGININPUTS = 'HANDLE_CHANGE_LOGININPUTS';
export const PLANET_REQUEST_SUCCESS='PLANET_REQUEST_SUCCESS';
export const SET_TIMER='SET_TIMER';
export const RESET_TIMER='RESET_TIMER';
export const PLANET_REQUEST_SUCCESS_SEARCHBOX='PLANET_REQUEST_SUCCESS_SEARCHBOX';
export const HANDLE_INPUT_SEARCHCHANGE='HANDLE_INPUT_SEARCHCHANGE';
export const CLEAR_STATE='CLEAR_STATE';

